# ldap root password for dn "uid=root"
# password="test", do not use this in production
RootPassword = "$6$1L2Zx6dCaWkHTIfT$SDGFU3PdbE2TN4Choqwy6pq4/L6xNAFtsnEchlEkbdEp1It2uNV.gX2S8DLEqWbq18NNPt7TFkbGKphdmFxqo1"
# etcd password of user root
# if empty or unset, auth of etcd is unused
EtcdPassword = ""

[[Host]]
HostName = "node1"
AdvertiseClient = "http://127.0.0.1:30011"
ListenClient = "http://127.0.0.1:30011"
AdvertisePeer = "http://127.0.0.1:30012"
ListenPeer = "http://127.0.0.1:30012"
Ldap = "127.0.0.1:1389"
TLSKey = "key.pem"
TLSCert = "cert.pem"

[[Host]]
HostName = "node2"
AdvertiseClient = "http://127.0.0.1:30021"
ListenClient = "http://127.0.0.1:30021"
AdvertisePeer = "http://127.0.0.1:30022"
ListenPeer = "http://127.0.0.1:30022"
Ldap = "127.0.0.1:1390"
TLSKey = "key.pem"
TLSCert = "cert.pem"
