oid:
- name: nisSchema
  oid: 1.3.6.1.1.1
schemas:
- oid: 1.3.6.1.4.1.1466.115.121.1.24
  link: https://tools.ietf.org/html/rfc4517#section-3.3.13
  name: GeneralizedTime
  desc: Generalized Time
- oid: 1.3.6.1.4.1.1466.115.121.1.26
  link: https://tools.ietf.org/html/rfc4517#section-3.3.15
  name: IA5String
  desc: IA5 String
- oid: 1.3.6.1.4.1.1466.115.121.1.26
  link: https://tools.ietf.org/html/rfc4517#section-3.3.16
  name: INTEGER
  desc: INTEGER
- oid: nisSchema.2.0
  link: https://tools.ietf.org/html/rfc2307#section-4
  name: posixAccount
  desc: Abstraction of an account with POSIX attributes
  sup: top
  auxiliary: true
  must:
  - cn
  - uid
  - uidNumber
  - gidNumber
  - homeDirectory
  may:
  - userPassword
  - loginShell
  - gecos
  - description
- oid: nisSchema.1.0
  link: https://tools.ietf.org/html/rfc2307#section-3
  name: uidNumber
  desc: An integer uniquely identifying a user in an administrative domain
  equality: integerMatch
  syntax: INTEGER
  single-value: true
- oid: nisSchema.1.1
  link: https://tools.ietf.org/html/rfc2307#section-3
  name: gidNumber
  desc: An integer uniquely identifying a group in an administrative domain
  equality: integerMatch
  syntax: INTEGER
  single-value: true
- oid: 2.5.18.1
  link: https://tools.ietf.org/html/rfc4512#section-3.4.2
  name: createTimestamp
  equality: generalizedTimeMatch
  ordering: generalizedTimeOrderingMatch
  syntax: GeneralizedTime
  single-value: true
  no-user-modification: true
  usage: directoryOperation
- oid: 2.5.18.2
  link: https://tools.ietf.org/html/rfc4512#section-3.4.2
  name: modifyTimestamp
  equality: generalizedTimeMatch
  ordering: generalizedTimeOrderingMatch
  syntax: GeneralizedTime
  single-value: true
  no-user-modification: true
  usage: directoryOperation